import { block } from './simplePortableTextCore';

export const pageBuilderDemoData = {
  _type: 'landingPage',
  title: 'Shared Landing Page Component Demo',
  slug: { _type: 'slug', current: 'shared-component-demo' },
  seoTitle: 'Shared Landing Page Component Demo',
  seoDescription: 'A local demo page that exercises the expanded FoundSM landing-page component catalog.',
  hideNavigation: false,
  hideFooter: false,
  sections: [
    {
      _type: 'eventHeroBlock',
      _key: 'event-hero-demo',
      eyebrow: 'Virtual Workshop',
      titleLines: ['Scale Smarter With', 'Paid Media'],
      accentLine: 'AI-Powered',
      description: 'A campaign-style hero for events, webinars, and resource launches with metadata, proof, and focused CTAs.',
      meta: [
        { _key: 'meta-date', icon: 'Date', label: 'Date', value: 'April 15, 2026' },
        { _key: 'meta-time', icon: 'Time', label: 'Time', value: '12:00 PM ET' },
        { _key: 'meta-place', icon: 'Place', label: 'Location', value: 'Virtual' },
      ],
      primaryCta: { label: 'Reserve Your Spot', href: '#demo-form' },
      secondaryCta: { label: 'View Agenda', href: '#demo-topics' },
      cardTitle: "What You'll Walk Away With",
      stats: [
        { _key: 'stat-topics', value: '6', label: 'Topics' },
        { _key: 'stat-minutes', value: '60', label: 'Minutes' },
        { _key: 'stat-frameworks', value: '3+', label: 'Frameworks' },
      ],
      chips: ['AI Strategy', 'Lead Gen', 'Automation', 'Creative Testing'],
      theme: 'dark',
    },
    {
      _type: 'proofMosaicBlock',
      _key: 'proof-mosaic-demo',
      title: 'Proof that helps buyers believe the promise',
      metrics: [
        { _key: 'metric-spend', eyebrow: 'Paid Media Spend', prefix: '$', value: '210', suffix: 'M', label: 'Managed in 2025' },
        { _key: 'metric-leads', eyebrow: 'Leads Generated', value: '1', suffix: 'M+', label: 'in 2025' },
        { _key: 'metric-years', value: '20', suffix: '+', label: 'Years performance marketing experience' },
      ],
      quote: {
        text: 'Found brings clarity to complex paid media systems and keeps every decision tied to business outcomes.',
        authorName: 'Marketing Leader',
        authorTitle: 'VP Growth',
        authorCompany: 'Enterprise Brand',
      },
      featureCard: {
        title: 'Independently owned, certified women-owned business',
        body: [block('Use this card for ownership, credentials, or a short trust proof with an optional CTA.')],
        cta: { label: 'Learn About Found', href: '/about-us/' },
      },
      videoUrl: 'https://placehold.co/900x640?text=Image+goes+here+-+900x640',
      imageAlt: 'Image goes here - replace with a proof-focused supporting image, 900x640.',
      theme: 'light',
      layoutPreset: 'mosaic',
    },
    {
      _type: 'featureTabsBlock',
      _key: 'feature-tabs-demo',
      title: 'A fuller tab system for complex offers',
      subtitle: 'Use layout presets when tabs need media panels, badge panels, or ecosystem-style dark panels.',
      idPrefix: 'expanded-tabs-demo',
      layoutPreset: 'ecosystem',
      autoRotate: true,
      theme: 'muted',
      tabs: [
        {
          _key: 'tab-data',
          title: 'Data Activation',
          body: [block('Connect first-party data to campaigns, reporting, and optimization loops.')],
          cta: { label: 'Explore Data', href: '/capabilities/data-intelligence/' },
          videoUrl: 'https://placehold.co/826x1070?text=Image+goes+here+-+826x1070',
          imageAlt: 'Image goes here - replace with a data activation visual, 826x1070.',
        },
        {
          _key: 'tab-media',
          title: 'Paid Media',
          body: [block('Build media systems that balance demand, efficiency, channel mix, and revenue quality.')],
          cta: { label: 'Explore Media', href: '/capabilities/paid-media/' },
          videoUrl: 'https://placehold.co/826x1070?text=Image+goes+here+-+826x1070',
          imageAlt: 'Image goes here - replace with a paid media visual, 826x1070.',
        },
      ],
    },
    {
      _type: 'cardGridBlock',
      _key: 'numbered-card-grid-demo',
      title: 'Numbered benefit cards',
      subtitle: 'Card grids now support numbered, topic, benefit, credential, icon, and standard variants.',
      columns: 3,
      variant: 'numbered',
      density: 'standard',
      theme: 'muted',
      cards: [
        { _key: 'benefit-one', number: '01', title: 'Proven frameworks', body: [block('Share a tested approach without turning the section into a dense essay.')] },
        { _key: 'benefit-two', number: '02', title: 'Vertical context', body: [block('Frame what is specific to the audience, market, or offer.')] },
        { _key: 'benefit-three', number: '03', title: 'Measurable next step', body: [block('Make the following CTA feel earned and specific.')] },
      ],
    },
    {
      _type: 'accordionBlock',
      _key: 'accordion-demo',
      eyebrow: 'The Found Difference',
      title: 'Accordion for dense proof',
      body: [block('Use accordions when the page needs several proof points but the first scan should stay clean.')],
      theme: 'light',
      layoutPreset: 'twoColumn',
      items: [
        { _key: 'advantage-one', title: 'Big picture view', body: [block('Show how all parts of the lead generation ecosystem work together.')] },
        { _key: 'advantage-two', title: 'Simplicity', body: [block('Make complex systems feel manageable for the buyer.')] },
        { _key: 'advantage-three', title: 'Results without fluff', body: [block('Keep the section grounded in business outcomes and clear measurement.')] },
      ],
    },
    {
      _type: 'logoBarBlock',
      _key: 'logo-marquee-demo',
      heading: 'Trusted partner ecosystem',
      displayMode: 'marquee',
      theme: 'muted',
      density: 'standard',
      logos: [
        {
          _key: 'logo-google',
          _type: 'logoItem',
          name: 'Platform logo 1',
          videoUrl: 'https://placehold.co/320x160?text=Image+goes+here+-+320x160',
          imageAlt: 'Image goes here - replace with platform logo 1, 320x160.',
        },
        {
          _key: 'logo-meta',
          _type: 'logoItem',
          name: 'Platform logo 2',
          videoUrl: 'https://placehold.co/320x160?text=Image+goes+here+-+320x160',
          imageAlt: 'Image goes here - replace with platform logo 2, 320x160.',
        },
        {
          _key: 'logo-microsoft',
          _type: 'logoItem',
          name: 'Platform logo 3',
          videoUrl: 'https://placehold.co/320x160?text=Image+goes+here+-+320x160',
          imageAlt: 'Image goes here - replace with platform logo 3, 320x160.',
        },
        {
          _key: 'logo-onetrust',
          _type: 'logoItem',
          name: 'Platform logo 4',
          videoUrl: 'https://placehold.co/320x160?text=Image+goes+here+-+320x160',
          imageAlt: 'Image goes here - replace with platform logo 4, 320x160.',
        },
      ],
    },
    {
      _type: 'peopleGridBlock',
      _key: 'people-grid-demo',
      title: 'People and speaker grid',
      intro: [block('Use this for leadership, speakers, author groups, or trust-building team sections.')],
      layout: 'centered',
      showImages: false,
      people: [
        { _key: 'person-one', name: 'Julie Warnecke', role: 'CEO' },
        { _key: 'person-two', name: 'Adam Persinger', role: 'Head of Strategic Media' },
        { _key: 'person-three', name: 'Caroline Stoner', role: 'Head of User Experience' },
      ],
    },
    {
      _type: 'modernCtaBlock',
      _key: 'cta-strip-demo',
      title: 'CTA strip preset for short next actions',
      body: [block('Use the strip preset when the page needs a concise mid-page or end-page action.')],
      cta: { label: 'Start the Conversation', href: '/contact-us/' },
      theme: 'green',
      align: 'split',
      layoutPreset: 'strip',
    },
    {
      _type: 'formLandingBlock',
      _key: 'form-landing-demo',
      eyebrow: 'Resource Access',
      title: 'Turn interest into a qualified next step',
      lead: 'Use this block for contact, newsletter, resource, and event capture pages.',
      intro: [block('This demo uses a placeholder HubSpot form ID so the editable layout can be reviewed locally.')],
      hubspotFormId: '00000000-0000-0000-0000-000000000000',
      portalId: '5045186',
      summary: [block('Follow up with a summary band that reinforces why the form is worth completing.')],
      variant: 'resource',
      theme: 'muted',
      showFormCard: true,
    },
  ],
};
